openapi: 3.0.0
info:
  title: Vectra API
  description: Swagger spec for Vectra API v1
  version: v1
  license:
    name: MIT
  contact:
    name: Vectra Support
    url: https://support.vectranetworks.com
    email: support@vectra.ai
servers:
  - url: 'https://{host}/api'
    variables:
      host:
        description: Hostname or IP of Brain
        default: localhost
security:
  - BasicAuth: []
paths:
  /detections:
    get:
      summary: Detection objects contain all the information related to security events detected on the network.
      parameters:
        - $ref: '#/components/parameters/c_score'
        - $ref: '#/components/parameters/c_score_gte'
        - $ref: '#/components/parameters/category'
        - $ref: '#/components/parameters/destination'
        - $ref: '#/components/parameters/detection_type'
        - $ref: '#/components/parameters/fields'
        - $ref: '#/components/parameters/host_id'
        - $ref: '#/components/parameters/is_targeting_key_asset'
        - $ref: '#/components/parameters/last_timestamp'
        - $ref: '#/components/parameters/max_id'
        - $ref: '#/components/parameters/min_id'
        - $ref: '#/components/parameters/note_modified_timestamp_gte'
        - $ref: '#/components/parameters/ordering'
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/page_size'
        - $ref: '#/components/parameters/proto'
        - $ref: '#/components/parameters/src_ip'
        - $ref: '#/components/parameters/t_score'
        - $ref: '#/components/parameters/t_score_gte'
        - $ref: '#/components/parameters/tags'
        # The following query parameters have been deprecated
        - name: type_vname
          in: query
          description: filter by the detection type (verbose name).
          deprecated: true
          schema:
            type: string
        - name: dst_port
          in: query
          description: filter by the destination porter in the detection detail set.
          deprecated: true
          schema:
            type: integer
        - name: inbound_ip
          in: query
          description: filter by the inbound_ip in the relayed comm set.
          deprecated: true
          schema:
            type: string
        - name: inbound_proto
          in: query
          description: filter by the inbound_proto in the relayed comm set.
          deprecated: true
          schema:
            type: string
        - name: inbound_port
          in: query
          description: filter by inbound_port in the relayed comm set.
          deprecated: true
          schema:
            type: integer
        - name: inbound_dns
          in: query
          description: filter by inbound_dns in the relayed comm set.
          deprecated: true
          schema:
            type: string
        - name: outbound_ip
          in: query
          description: filter by the outbound_ip in the relayed comm set.
          deprecated: true
          schema:
            type: string
        - name: outbound_port
          in: query
          description: filter by the outbound_port in the relayed comm set.
          deprecated: true
          schema:
            type: integer
        - name: outbound_dns
          in: query
          description: filter by the outbound_dns in teh relayed comm set.
          deprecated: true
          schema:
            type: string
        - name: dns_ip
          in: query
          description: filter by the dns_ip in the dns_set.
          deprecated: true
          schema:
            type: string
        - name: dns_request
          in: query
          description: filter by the dns_request in the dns_set.
          deprecated: true
          schema:
            type: string
        - name: resp_code
          in: query
          description: filter by the resp_code in the dns_set.
          deprecated: true
          schema:
            type: integer
        - name: resp
          in: query
          description: filter by the resp in the dns_set.
          deprecated: true
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/DetectionsResponse200'
        default:
          $ref: '#/components/responses/DefaultResponse'
  /detections/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          $ref: '#/components/responses/DetectionResponse200'
        default:
          $ref: '#/components/responses/DefaultResponse'
  /hosts:
    get:
      parameters:
        - $ref: '#/components/parameters/c_score'
        - $ref: '#/components/parameters/c_score_gte'
        - $ref: '#/components/parameters/fields'
        - $ref: '#/components/parameters/key_asset'
        - $ref: '#/components/parameters/last_detection_timestamp'
        - $ref: '#/components/parameters/last_source'
        - $ref: '#/components/parameters/mac_address'
        - $ref: '#/components/parameters/max_id'
        - $ref: '#/components/parameters/min_id'
        - $ref: '#/components/parameters/name'
        - $ref: '#/components/parameters/note_modified_timestamp_gte'
        - $ref: '#/components/parameters/ordering'
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/page_size'
        - $ref: '#/components/parameters/state'
        - $ref: '#/components/parameters/t_score'
        - $ref: '#/components/parameters/t_score_gte'
        - $ref: '#/components/parameters/tags'
      responses:
        '200':
          $ref: '#/components/responses/HostsResponse200'
        default:
          $ref: '#/components/responses/DefaultResponse'
  /hosts/{id}:
    get:
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          $ref: '#/components/responses/HostResponse200'
        default:
          $ref: '#/components/responses/DefaultResponse'
  /system/info:
    get:
      responses:
        '200':
          $ref: '#/components/responses/SystemInfoResponse200'
        default:
          $ref: '#/components/responses/DefaultResponse'
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  parameters:
    id:
      name: id
      in: path
      required: true
      schema:
        type: integer
    fields:
      name: fields
      in: query
      description: Filter objects listed
      schema:
        type: array
        items:
          type: string
    page:
      name: page
      in: query
      description: Page Number.
      schema:
        type: integer
    page_size:
      name: page_size
      in: query
      description: Page size.
      schema:
        type: integer
    ordering:
      name: ordering
      in: query
      description: Orders records by last timestamp, threat score and certainty score.
      schema:
        type: string
        enum:
          - c_score
          - -c_score
          - last_timestamp
          - -last_timestamp
          - t_score
          - -t_score
    name:
      name: name
      in: query
      description: filter by name.
      schema:
        type: string
    state:
      name: state
      in: query
      description: filter by state.
      schema:
        type: string
        enum:
          - active
          - inactive
    min_id:
      name: min_id
      in: query
      description: '>= the id provided.'
      schema:
        type: integer
    max_id:
      name: max_id
      in: query
      description: '<= the id provided.'
      schema:
        type: integer
    t_score:
      name: t_score
      in: query
      description: filter by threat score.
      schema:
        type: integer
    t_score_gte:
      name: t_score_gte
      in: query
      description: 'filter by threat score >= the score provided.'
      schema:
        type: integer
    c_score:
      name: c_score
      in: query
      description: filter by certainty score.
      schema:
        type: integer
    c_score_gte:
      name: c_score_gte
      in: query
      description: 'filter by certainty score >= the score provided.'
      schema:
        type: integer
    note_modified_timestamp_gte:
      name: note_modified_timestamp_gte
      in: query
      description: 'filter by note_modified_timestamp >= the timestamp provided.'
      schema:
        type: string
    category:
      name: category
      in: query
      description: filter by the detection category.
      schema:
        type: string
        enum:
          - botnet
          - command
          - exfiltration
          - lateral
          - reconnaissance
    detection_type:
      name: detection_type
      in: query
      description: filter by the name of the threat detected.
      schema:
        type: string
    last_source:
      name: last_source
      in: query
      schema:
        type: string
    last_detection_timestamp:
      name: last_detection_timestamp
      in: query
      schema:
        type: string
    tags:
      name: tags
      in: query
      schema:
        type: array
        items:
          type: string
    key_asset:
      name: key_asset
      in: query
      schema:
        type: boolean
    mac_address:
      name: mac_address
      in: query
      schema:
        type: string
    src_ip:
      name: src_ip
      in: query
      schema:
        type: string
    last_timestamp:
      name: last_timestamp
      in: query
      schema:
        type: string
    host_id:
      name: host_id
      in: query
      schema:
        type: integer
    destination:
      name: destination
      in: query
      schema:
        type: string
    proto:
      name: proto
      in: query
      schema:
        type: string
    is_targeting_key_asset:
      name: is_targeting_key_asset
      in: query
      schema:
        type: boolean
  responses:
    DefaultResponse:
      description: unexpected error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    DetectionsResponse200:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Detections'
    DetectionResponse200:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Detection'
    HostsResponse200:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Hosts'
    HostResponse200:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Host'
    SystemInfoResponse200:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SystemInfo'
  schemas:
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string
    Detections:
      type: object
      properties:
        count:
          description: Number of returned objects.
          type: integer
        next:
          description: URL for next page.
          type: string
        previous:
          description: URL for previous page.
          type: string
        results:
          description: The list of detections.
          type: array
          items:
            $ref: '#/components/schemas/Detection'
      required:
        - count
        - results
    Detection:
      type: object
      properties:
        c_score:
          type: integer
          description: The certainty score attributed to the detection.
          deprecated: false
        category:
          type: string
          description: The category of the vname attack detected.
        description:
          type: string
          nullable: true
        detection_detail_set:
          type: array
          items:
            $ref: '#/components/schemas/DetectionDetails'
          description: Indicates the number of nested records.
          deprecated: true
        dns_set:
          type: array
          items:
            type: string
          deprecated: true
        first_timestamp:
          type: string
          description: The timestamp when the event was first detected.
        host:
          type: string
          description: The URL that links directly to the host record.
        id:
          type: integer
          description: Object ID.
        last_timestamp:
          type: string
          description: The timestamp when the event was last detected.
        relayed_comm_set:
          type: array
          items:
            type: string
          deprecated: false
        sensor_luid:
          type: string
          description: The sensor local unique ID where this flow was detected from.
        src_ip:
          type: string
          description: The source IP address of the host attributed to the security event.
        state:
          type: string
          description: The state of the detection.
          enum:
            - inactive
            - active
        summary:
          type: object
          nullable: true
        t_score:
          type: integer
          description: The threat score attributed to the detection.
        tags:
          type: array
          items:
            type: string
        targets_key_asset:
          type: boolean
        triage_rule_id:
          type: string
          nullable: true
        type_vname:
          type: string
          description: The name of the threat detected.
          deprecated: true
        url:
          type: string
          description: The URL that links directly to the detection record.
    DetectionDetails:
      type: object
      properties:
        count:
          type: integer
          description: Detection detail count.
          nullable: true
        description:
          type: string
          description: System generated description of the event.
        dst_dns:
          type: string
          nullable: true
        dst_geo:
          type: string
          nullable: true
        dst_host_id:
          type: integer
        dst_ip:
          type: string
        dst_port:
          type: integer
        first_timestamp:
          type: string
          description: The timestamp when the event was first detected.
        id:
          type: integer
        last_timestamp:
          type: string
          description: The timestamp when the event was last detected.
        proto:
          type: string
          description: Protocol used in the communications.
        total_bytes_sent:
          type: integer
          description: Total bytes sent by the client.
        total_bytes_rcvd:
          type: integer
          description: Total bytes received by the client.
        url:
          type: string
          description: The URL that links directory to this record.
    Hosts:
      type: object
      properties:
        count:
          description: Number of returned objects.
          type: integer
        next:
          description: URL for next page.
          type: string
        previous:
          description: URL for previous page.
          type: string
        results:
          description: The list of detections.
          type: array
          items:
            $ref: '#/components/schemas/Host'
      required:
        - count
        - results
    Host:
      type: object
      properties:
        c_score:
          description: The current certainty score correlated to this host.
          type: integer
        detection_set:
          description: List of detections for host.
          type: array
          items:
            type: string
        host_artifact_set:
          description: List of host artifacts observed for the host.
          type: array
          items:
            $ref: '#/components/schemas/HostArtifact'
        id:
          type: integer
        key_asset:
          type: boolean
        last_detection_timestamp:
          type: string
        last_source:
          type: string
        name:
          type: string
        new_host_pointer:
          type: string
          nullable: true
          deprecated: true
        note:
          description: User defined note added to the host
          type: string
          nullable: true
        owner_name:
          description: Probable owner of the host
          type: string
          nullable: true
        sensor_luid:
          type: string
        state:
          type: string
          enum:
            - active
            - inactive
        t_score:
          type: integer
        tags:
          type: array
          items:
            type: string
        targets_key_asset:
          type: boolean
        url:
          type: string
    HostArtifact:
      type: object
    SystemInfo:
      type: object
      properties:
        colossus_mode:
          type: string
        platform_version:
          type: string
        serial_number:
          type: string
        ui_version:
          type: string
        version:
          type: string
