openapi: 3.0.0
info:
  title: Vectra API
  description: Swagger spec for Vectra API v2
  version: v2
  license:
    name: MIT
  contact:
    name: Vectra Support
    url: https://support.vectranetworks.com
    email: support@vectra.ai
servers:
- url: https://{host}/api/v2
  variables:
    host:
      description: Hostname or IP of Brain
      default: localhost
security:
- TokenAuth: []
paths:
  /detections:
    get:
      summary: Detection objects contain all the information related to security events detected on the network.
      parameters:
      - name: category
        in: query
        description: The category of the vname attack detected.
        schema:
            type: string
            enum:
            - COMMAND AND CONTROL
            - BOTNET
            - RECONNAISSANCE
            - LATERAL MOVEMENT
            - EXFILTRATION
      - name: page
        in: query
        description: Page Number.
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Detections'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  securitySchemes:
    TokenAuth:
      type: apiKey
      name: Authorization
      in: header
  schemas:
    Error:
      required:
      - code
      - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    Detections:
      type: object
      properties:
        count:
          description: Number of returned objects
          type: integer
        next:
          description: URL for next page
          type: string
        previous:
          description: URL for previous page
          type: string
        results:
          description: The list of detections
          type: array
          items:
            $ref: "#/components/schemas/Detection"
      required:
      - count
      - results
    Detection:
      type: object
      properties:
        id:
          type: integer
        detection_type:
          description: Name of the detection as shown by in UI.
          type: string
        summary:
          type: object
          description: Summary of detection.
  responses:
    DetectionsResponse200:
      description: OK
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Detections"
