openapi: 3.0.0
info:
  title: Vectra API
  description: Swagger spec for Vectra API v2
  version: v2
  license:
    name: MIT
  contact:
    name: Vectra Support
    url: https://support.vectranetworks.com
    email: support@vectra.ai
servers:
- url: https://{host}/api/v2
  variables:
    host:
      description: Hostname or IP of Brain
      default: localhost
security:
- TokenAuth: []
paths:
  /detections:
    get:
      summary: Detection objects contain all the information related to security events detected on the network.
      parameters:
      - name: category
        in: query
        description: The category of the vname attack detected.
        schema:
            type: string
            # TODO: enumerate categories. hard to because we alias a lot of things
      - name: page
        in: query
        schema:
          type: integer
      - description: '>= the id provided'
        in: query
        name: min_id
        schema:
          type: string
      - description: '<= the id provided'
        in: query
        name: max_id
        schema:
          type: integer
      - description: 'filter by state: active, inactive, ignored, ignored4all'
        in: query
        name: state
        schema:
          type: string
          enum:
          - active
          - inactive
      - description: filter by the detection description
        in: query
        name: description
        schema:
          type: string
      - description: filter by the detection type (verbose name)
        in: query
        name: detection_type
        schema:
          type: string
      - description: filter by the detection type (verbose name)
        in: query
        name: detection
        schema:
          type: string
      - description: filter by the detection category
        in: query
        name: detection_category
        schema:
          type: string
      - description: filter by source (ip address)
        in: query
        name: src_ip
        schema:
          type: string
      - description: filter by threat score
        in: query
        name: threat
        schema:
          type: integer
      - description: 'filter by threat score >= the score provided'
        in: query
        name: threat_gte
        schema:
          type: integer
      - description: filter by certainty score
        in: query
        name: certainty
        schema:
          type: integer
      - description: 'filter by certainty score >= the score provided'
        in: query
        name: certainty_gte
        schema:
          type: integer
      - description: filter by last_timestamp
        in: query
        name: last_timestamp
        schema:
          type: string
      - description: filter by id of the host object a detection is attributed to
        in: query
        name: host_id
        schema:
          type: string
      - name: tags
        description: User defined tags added to the detection.
        in: query
        schema:
          type: array
          items:
            type: string
      - description: 'filter by detections that are targeting a key asset: True, False'
        in: query
        name: is_targeting_key_asset
        schema:
          type: boolean
      - description: 'filter by note_modified_timestamp >= the timestamp provided: 2017-12-31T16:55:50Z'
        in: query
        name: note_modified_timestamp_gte
        schema:
          type: string
      responses:
        '200':
          $ref: '#/components/responses/Detections200'
        default:
          $ref: '#/components/responses/Default'
  /search/hosts:
    get:
      parameters:
      - $ref: '#/components/parameters/page_size'
      - $ref: '#/components/parameters/query_string'
      responses:
        '200':
          $ref: '#/components/responses/SearchHosts200'
        default:
          $ref: '#/components/responses/Default'
  /search/detections:
    get:
      parameters:
      - $ref: '#/components/parameters/page_size'
      - $ref: '#/components/parameters/query_string'
      responses:
        '200':
          $ref: '#/components/responses/SearchDetections200'
        default:
          $ref: '#/components/responses/Default'
  /proxies:
    get:
      responses:
        '200':
          $ref: '#/components/responses/Proxies200'
        default:
          $ref: '#/components/responses/Default'
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProxiesBody'
      responses:
        '200':
          $ref: '#/components/responses/200'
        '201':
          $ref: '#/components/responses/201'
        default:
          $ref: '#/components/responses/Default'
  /proxies/{id}:
    get:
      parameters:
      - $ref: '#/components/parameters/id'
      responses:
        '200':
          $ref: '#/components/responses/Proxy200'
        default:
          $ref: '#/components/responses/Default'
    patch:
      parameters:
        - $ref: '#/components/parameters/id'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProxiesBody'
      responses:
        '200':
          $ref: '#/components/responses/200'
        '204':
          $ref: '#/components/responses/204'
        default:
         $ref: '#/components/responses/Default'
  /threatFeeds:
    get:
      responses:
        '200':
          $ref: '#/components/responses/ThreatFeeds200'
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ThreatFeedsBody'
      responses:
        '200':
          $ref: '#/components/responses/200'
        '201':
          $ref: '#/components/responses/201'
        default:
         $ref: '#/components/responses/Default'
  /threatFeeds/{id}:
    get:
      parameters:
      - $ref: '#/components/parameters/id'
      responses:
        '200':
          $ref: '#/components/responses/ThreatFeed200'
        default:
         $ref: '#/components/responses/Default'
components:
  securitySchemes:
    TokenAuth:
      type: apiKey
      name: Authorization
      in: header
  parameters:
    id:
      name: id
      in: path
      required: true
      schema:
        type: integer
    page_size:
      name: page_size
      in: query
      schema:
        type: integer
    query_string:
      name: query_string
      in: query
      schema:
        type: string
  responses:
    200:
      description: OK
    201:
      description: OK
    204:
      description: OK
    Default:
      description: unexpected error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Detections200:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Detections'
    SearchHosts200:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Hosts'
    SearchDetections200:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Detections'
    Proxies200:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Proxies'
    Proxy200:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Proxy'
    ThreatFeeds200:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ThreatFeeds'
    ThreatFeed200:
      description: OK
      content:
        appliction/json:
          schema:
            $ref: '#/components/schemas/ThreatFeed'
  schemas:
    Error:
      required:
      - code
      - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    Detections:
      type: object
      properties:
        count:
          description: Number of returned objects
          type: integer
        next:
          description: URL for next page
          type: string
        previous:
          description: URL for previous page
          type: string
        results:
          description: The list of detections
          type: array
          items:
            $ref: "#/components/schemas/Detection"
      required:
      - count
      - results
    Detection:
      type: object
      properties:
        id:
          type: integer
        detection_type:
          description: Name of the detection as shown by in UI.
          type: string
        summary:
          type: object
          description: Summary of detection.
        detection_category:
          type: string
        dst_port:
          type: integer
        dst_geo:
          type: string
        src_ip:
          type: string
        state:
          type: string
        threat:
          type: integer
        certainty:
          type: integer
        first_timestamp:
          type: string
        last_timestamp:
          type: string
        detection_detail_set:
          type: object
        description:
          type: string
        destination:
          type: string
        count:
          type: integer
        proto:
          type: string
        total_bytes_sent:
          type: integer
        total_bytes_rcvd:
          type: integer
        url:
          type: string
        sensor_name:
          type: string
        host:
          type: string
        grouped_details:
          type: object
        tags:
          description: User defined tags added to the detection.
          type: array
          items:
            type: string
        is_targeting_key_asset:
          type: boolean
        campaign_summaries:
          type: object
        note:
          type: string
        note_modified_by:
          type: string
        note_modified_timestamp:
          type: string
        assigned_to:
          type: string
        assigned_date:
          type: string
    Hosts:
      type: object
    Proxies:
      type: object
      properties:
        meta:
          type: object
          properties:
            count:
              type: integer
        proxies:
          type: array
          items:
            $ref: '#/components/schemas/Proxy'
    ProxiesBody:
      type: object
      properties:
        proxy:
          type: object
          properties:
            address:
              type: string
            considerProxy:
              type: boolean
    Proxy:
      type: object
      properties:
        source:
          type: string
          enum:
            - user
            - cognito
        id:
          type: string
        considersProxy:
          description: Whether to consider the object as a proxy or not
          type: boolean
        address:
          description: The IP address for the proxy object
          type: string
    ThreatFeeds:
      type: object
      properties:
        meta:
          type: object
          properties:
            count:
              type: integer
        threatFeeds:
          type: array
          items:
            $ref: '#/components/schemas/ThreatFeed'
    ThreatFeed:
      type: object
      properties:
        name:
          type: string
        duration:
          type: integer
        category:
          type: string
          enum:
          - cnc
          - lateral
          - exfil
        indicatorType:
          type: string
          enum:
          - Anonymization
          - C2
          - Exfiltration
          - Malware
          - Artifacts
          - Watchlist
        certainty:
          type: string
          enum:
          - Low
          - Medium
          - High
        data:
          type: object
          nullable: true
    ThreatFeedsBody:
      type: object
      properties:
        threatFeed:
          $ref: '#/components/schemas/ThreatFeed'
